package it.zeze.fantaformazioneweb.entity.wrapper;

import java.util.HashSet;
import java.util.Set;

import it.zeze.fantaformazioneweb.entity.Squadre;

/**
 * Squadre generated by hbm2java
 */
public class SquadreWrap implements java.io.Serializable {

	private static final long serialVersionUID = -335784320484808798L;
	
	private int id;
	private String nome;
	private Set<GiocatoriWrap> giocatoris = new HashSet<GiocatoriWrap>(0);
	private Set<CalendarioWrap> calendariosForIdSquadraCasa = new HashSet<CalendarioWrap>(0);
	private Set<CalendarioWrap> calendariosForIdSquadraFuoriCasa = new HashSet<CalendarioWrap>(0);
	
	public SquadreWrap(Squadre toCopy) {
		id = toCopy.getId();
		nome = toCopy.getNome();
	}
	
	public Squadre unwrap(){
		Squadre toReturn = new Squadre(id, nome);
		return toReturn;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<GiocatoriWrap> getGiocatoris() {
		return giocatoris;
	}

	public void setGiocatoris(Set<GiocatoriWrap> giocatoris) {
		this.giocatoris = giocatoris;
	}

	public Set<CalendarioWrap> getCalendariosForIdSquadraCasa() {
		return calendariosForIdSquadraCasa;
	}

	public void setCalendariosForIdSquadraCasa(Set<CalendarioWrap> calendariosForIdSquadraCasa) {
		this.calendariosForIdSquadraCasa = calendariosForIdSquadraCasa;
	}

	public Set<CalendarioWrap> getCalendariosForIdSquadraFuoriCasa() {
		return calendariosForIdSquadraFuoriCasa;
	}

	public void setCalendariosForIdSquadraFuoriCasa(Set<CalendarioWrap> calendariosForIdSquadraFuoriCasa) {
		this.calendariosForIdSquadraFuoriCasa = calendariosForIdSquadraFuoriCasa;
	}
}
